Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: iowa-technology-summit-2023
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Value: !Ref DataBucket
    Export:
      Name: AIAssistedDataBucketName
