name: Deploy Bucket

on:
  push:
    paths:
      - 'iac/**'
      - '.github/workflows/bucket.yml'
    branches: [ main ]

permissions:
  id-token: write # This is required for aws oidc connection
  contents: write # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-2
          role-session-name: GitHub-OIDC
          role-duration-seconds: 1200

      - name: Deploy CloudFormation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: iowa-technology-summit-2023-private-bucket
          template: iac/bucket.yml
          tags: '[{"Key": "owner", "Value": "Matt Vincent"}]'
          capabilities: CAPABILITY_NAMED_IAM
