name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: ./project
      run: |
        python -m pip install -r requirements.txt

    - name: Set environment variables
      env:
        ACTITIME_URL: ${{ secrets.ACTITIME_URL }}
        ACTITIME_USERNAME: ${{ secrets.ACTITIME_USERNAME }}
        ACTITIME_PASSWORD: ${{ secrets.ACTITIME_PASSWORD }}
      run: |
        echo "ACTITIME_URL=${ACTITIME_URL}" >> $GITHUB_ENV
        echo "ACTITIME_USERNAME=${ACTITIME_USERNAME}" >> $GITHUB_ENV
        echo "ACTITIME_PASSWORD=${ACTITIME_PASSWORD}" >> $GITHUB_ENV

    - name: Run unit tests with coverage
      working-directory: ./project
      run: |
        coverage run --source . -m unittest discover -s tests

    - name: Print coverage report
      working-directory: ./project
      run: |
        coverage report

    - name: Generate HTML coverage report
      working-directory: ./project
      run: |
        coverage html

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: project/htmlcov
